name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  DOCKER_HUB_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
  DOCKER_HUB_ACCESS_TOKEN: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
  REPOSITORY_NAME: ${{secrets.REPOSITORY_NAME}}
  PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
  USERNAME: ${{secrets.USERNAME}}
  HOSTNAME: ${{secrets.HOSTNAME}}


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: docker login
      run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_ACCESS_TOKEN
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t $REPOSITORY_NAME --tag $DOCKER_HUB_USERNAME/$REPOSITORY_NAME

    - name: Create container
      run: docker run -t -d $REPOSITORY_NAME

    - name: push to a dockerhub
      run: docker push $DOCKER_HUB_USERNAME/$REPOSITORY_NAME

    - name: create a file to give permission
      run: echo $PRIVATE_KEY > key.pem && chmod +600 key.pem

    - name: connect  machine
      run: ssh -i 'key.pem' ubuntu@ec2-3-82-38-13.compute-1.amazonaws.co