name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  DOCKER_HUB_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
  DOCKER_HUB_ACCESS_TOKEN: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
  REPOSITORY_NAME: ${{secrets.REPOSITORY_NAME}}
  PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
  USERNAME: ${{secrets.USERNAME}}
  HOSTNAME: ${{secrets.HOSTNAME}}


jobs:

  build:


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_ACCESS_TOKEN

    - name: Build the Docker image
      run: docker build . -t $REPOSITORY_NAME --tag $DOCKER_HUB_USERNAME/$REPOSITORY_NAME

    - name: Create container
      run: docker run -t -d  $REPOSITORY_NAME

    - name: push to a dockerhub
      run: docker push $DOCKER_HUB_USERNAME/$REPOSITORY_NAME

  deploy:
      needs: build
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - name: deploy in EC2 machine
          run: |
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} '
            
            ## run container update
            docker pull $DOCKER_HUB_USERNAME/$REPOSITORY_NAME:latest '
#            docker rm -f $(docker ps -aq) '                ##USING ONLY IN LOCAL DEVELOPMENT
#            docker run -d -p 3000:3000 ${DOCKER_HUB_USERNAME}/${REPOSITORY_NAME} '

            




